[tool.poetry]
name = "fastapi-starter"
version = "0.1.0"
description = ""
authors = ["David Harting <david.harting@hey.com>"]
readme = "README.md"
packages = [{include = "fastapi_starter"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
