name: FastAPI starter CI
on: [push]
jobs:
  code-hygiene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install
      - name: Check formatting
        run: poetry run python tasks.py format
      - name: Check if imports are sorted
        run: poetry run python tasks.py sort-imports
      - name: Lint
        run: poetry run python tasks.py lint
      - name: Typecheck
        run: poetry run python tasks.py typecheck
      - name: Test
        run: poetry run python tasks.py test
